version: "3.8"

services:
  cpp-app:
    build: .
    container_name: student_info_system
    stdin_open: true
    tty: true
    version: '3.8'

services:
  db:
    image: postgres:latest  # İşte "Base Image" burası
    container_name: student_info_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: student_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


#Container resource limits
  services:
  cpp-app:
    image: elifkokden/cpp-app:latest
    container_name: cpp-app
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M
    restart: unless-stopped

    services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data


#healthcheck

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5


  
